name: Deploy to GHCR

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DTEST_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DTEST_AWS_KEY_SECRET }}
          aws-region: us-east-1

      - name: Build and Push Django Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cicd/django/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/django:latest
          build-args: |
            DTEST_AWS_KEY_ID=${{ secrets.DTEST_AWS_KEY_ID }}
            DTEST_AWS_KEY_SECRET=${{ secrets.DTEST_AWS_KEY_SECRET }}
            PROD_DJANGO_SECRET_KEY=${{ secrets.PROD_DJANGO_KEY }}
            DTEST_DB_USER=${{ secrets.DTEST_DB_USER }}
            DTEST_DB_PASSWORD=${{ secrets.DTEST_DB_PASSWORD }}
            DTEST_DB_NAME=${{ vars.DTEST_DB_NAME }}

      - name: Build and push Nginx Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cicd/nginx/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/nginx:latest
