name: Deploy to GHCR

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Django Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cicd/django/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/django:latest

    - name: Build and push Nginx Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cicd/nginx/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/nginx:latest
