name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production

    env:
      # Any environment variables prefixed with TF_VAR_ are automatically read as Terraform variables.
      TF_VAR_ghcr_token: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform 1.5
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5

      - name: Terraform Init
        run: |
          terraform -chdir=terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_S3_BUCKET }}" \
            -backend-config="dynamodb_table=${{ vars.TF_STATE_DYNAMODB_TABLE }}" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="key=state/production/terraform.tfstate"

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=terraform apply -auto-approve -input=false

        # Output the standard output, error output, and exit code of the Terraform apply step
      - run: echo "${{ steps.apply.outputs.stdout }}"
        continue-on-error: true
      - run: echo "${{ steps.apply.outputs.stderr }}"
        continue-on-error: true
      - run: echo "${{ steps.apply.outputs.exitcode }}"
        continue-on-error: true
