name: Terraform Plan

on:
#   pull_request:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: production

    env:
      TF_VAR_ghcr_token: ${{ secrets.GHCR_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
